#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/nwmc3271/Dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/nwmc3271/Dev/flutter_staggered_grid_view/example"
export "FLUTTER_TARGET=/Users/nwmc3271/Dev/flutter_staggered_grid_view/example/lib/main_issue_23.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/nwmc3271/Dev/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "EXTRA_FRONT_END_OPTIONS=--enable-experiment%3Dnon-nullable"
export "EXTRA_GEN_SNAPSHOT_OPTIONS=--enable-experiment%3Dnon-nullable"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
